### ISSUE TITLE
Please submit a new version to npm

### ISSUE THREAD

**Issue by bacongravy** [paulmillr/micro-promisify#6]
I'd like to use this project by loading it from unpkg:

https://unpkg.com/browse/micro-promisify@0.1.1/index.js

However, the version up there (and on npm) is out of date with respect to the repository contents.

Could you please tag the latest changes and push them to npm? Thanks!

**Comment by jirikrepl** [comment]
+1

**Comment by paulmillr** [comment]
done

**Comment by bacongravy** [comment]
Thanks! I realized that unpkg doesn't set the MIME types properly, so for posterity's sake, here's the URL I am actually using:

https://cdn.jsdelivr.net/npm/micro-promisify@0.2.0/index.js
